### ISSUE TITLE
VIP question

### ISSUE THREAD

**Issue by speedkup** [vdupain/terraform-proxmox-talos-k8s-cluster#4]
Hello,

Thank you for making this module available, it's very useful.

I have two questions:

    Is there a setting somewhere to prevent randomly generated VM IDs from being created?
    Is your module also usable when setting up a VIP IP? Unfortunately, I haven't been able to get it working that way.

Thanks in advance for your reply.

**Comment by vdupain** [comment]
Hello
For the randomy generated VM IDs, it's come from this configuration: https://github.com/vdupain/terraform-proxmox-talos-k8s-cluster/blob/main/modules/vms_proxmox/providers.tf#L6. It's hard coded and it would be great to be configurable with variable.
For the VIP IP, with dhcp enabled, it's not necessary as it takes the 1st control plane IP. Otherwise you have to set cluster.endpoint varaible with your VIP IP.

**Comment by vdupain** [comment]
randomy generated VM IDs fixed: disable by default
https://github.com/vdupain/terraform-proxmox-talos-k8s-cluster/commit/71a1d35b8a4a7146a150050d6096c0779b58e42b

**Comment by speedkup** [comment]
I tried adding the VIP lines to the control-plane template and using the IP address specified there as the endpoint, but unfortunately it didn't work.

What am I doing wrong? Could you please help me?

Thank you in advance.

```yaml
# control-plane.yaml.tmpl

machine:
  install:
    disk: ${install_disk}
  network:
    hostname: ${hostname}
    interfaces:
      - interface: ens18
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: 192.168.1.127
  time:
    servers:
      - pool.ntp.org

cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
  proxy:
    disabled: true
  inlineManifests:
  - name: cilium-values
    contents: |
      ${indent(6, cilium_values)}
  - name: cilium-bootstrap
    contents: |
      ${indent(6, cilium_install)}
```

```yaml
# variables.auto.tfvars

cluster = {
  name     = "talos-dev"
  gateway  = "192.168.1.1"
  cidr     = 24
  endpoint = "192.168.1.127" # VIP ip address
}

vms = {
  "k8s-cp-1" = {
    host_node      = "pve"
    machine_type   = "controlplane"
    ip             = "192.168.1.121"
    cpu            = 4
    ram_dedicated  = 4096
    os_disk_size   = 10
#    data_disk_size = 50
    datastore_id   = "local-lvm"
    install_disk   = "/dev/sda"
  }
  "k8s-cp-2" = {
    host_node      = "pve"
    machine_type   = "controlplane"
    ip             = "192.168.1.122"
    cpu            = 4
    ram_dedicated  = 4096
    os_disk_size   = 10
#    data_disk_size = 50
    datastore_id   = "local-lvm"
    install_disk   = "/dev/sda"
  }
  "k8s-cp-3" = {
    host_node      = "pve"
    machine_type   = "controlplane"
    ip             = "192.168.1.123"
    cpu            = 4
    ram_dedicated  = 4096
    os_disk_size   = 10
#    data_disk_size = 50
    datastore_id   = "local-lvm"
    install_disk   = "/dev/sda"
  }
  "k8s-wn-1" = {
    host_node      = "pve"
    machine_type   = "worker"
    ip             = "192.168.1.124"
    cpu            = 4
    ram_dedicated  = 4096
    os_disk_size   = 10
#    data_disk_size = 50
    datastore_id   = "local-lvm"
    install_disk   = "/dev/sda"
  }
}

**Comment by vdupain** [comment]
Maybe try this configuration in your control-plane.yaml.tmpl
```
machine:
  network:
    hostname: ${hostname}
    interfaces:
      - deviceSelector:
          physical: true
        vip:
          ip: ${cluster VIP IP}
```
